version: '3'

volumes:
    postgres_data: {}

services:
    postgres:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"

    django:
        build:
            context: .
            dockerfile: docker/django/Dockerfile
        command: /start-dev.sh
        depends_on:
            - postgres
        environment:
            - POSTGRES_USER=postgres
            - USE_DOCKER=yes
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file: .env
