version: '3'

volumes:
    pg_volume:
    media_volume:
    static_volume:

services:
    postgres:
        image: mdillon/postgis:11
        container_name: postgres
        volumes:
            - pg_volume:/var/lib/postgresql/data
        expose:
            - 5432
        env_file: .env

    django:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
        depends_on:
            - postgres
        volumes:
            - media_volume:/app/media/
            - static_volume:/app/staticfiles/
        expose:
          - 8000
        env_file: .env

    django-admin:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django-admin
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
        depends_on:
            - postgres
        volumes:
            - media_volume:/app/media/
            - static_volume:/app/staticfiles/
        ports:
            - "8000:8000"
        env_file: .admin.env

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - .nginx/nginx.conf:/etc/nginx/nginx.conf
            - .nginx/error.log:/etc/nginx/error.log
            - .nginx/cache/:/etc/nginx/cache
            - /etc/letsencrypt/:/etc/letsencrypt/
            - static_volume:/static/
            - media_volume:/media/
        ports:
            - 80:80
            - 443:443
        depends_on:
          - django
