version: '3'

volumes:
    pg_volume:
    media_volume:
    static_volume:

services:
    postgres:
        image: mdillon/postgis:11
        container_name: postgres
        volumes:
            - pg_volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file: .env

    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - postgres
        volumes:
            - .:/app
            - media_volume:/app/media/
            - static_volume:/app/staticfiles/
        ports:
            - "8000:8000"
        env_file: .env
