version: '3'

volumes:
    pg_volume:

services:
    postgres:
        image: mdillon/postgis:11
        volumes:
            - pg_volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file: .env

    django:
        build:
            context: .
            dockerfile: docker/django/Dockerfile
        command: /start-dev.sh
        depends_on:
            - postgres
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file: .env
