# Generated by Django 2.2.6 on 2019-10-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'ordering': ('id',)},
        ),
    ]
