# Generated by Django 2.2.6 on 2019-10-08 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=150)),
                ('os', models.CharField(max_length=150)),
                ('browser', models.CharField(max_length=150)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.QrCode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
