# Generated by Django 2.2.6 on 2019-10-18 19:26

from django.db import migrations, models
import pendulum


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='_datetime',
            field=models.DateTimeField(default=pendulum.now),
        ),
    ]
