# Generated by Django 2.2.6 on 2019-10-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_access__datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='qrcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='qr.QrCode'),
        ),
    ]
