# Generated by Django 2.2.3 on 2019-09-16 01:09

from django.db import migrations, models
import django.db.models.deletion
import qr.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=qr.utils.get_qrcode_img_path)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logos.Logo')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_qr.qrcode_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileQrCode',
            fields=[
                ('qrcode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qr.QrCode')),
                ('file', models.FileField(upload_to=qr.utils.get_file_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('qr.qrcode',),
        ),
        migrations.CreateModel(
            name='URLQrCode',
            fields=[
                ('qrcode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qr.QrCode')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('qr.qrcode',),
        ),
    ]
