# Generated by Django 2.2.3 on 2019-07-18 21:45

from django.db import migrations, models
import qr.utils


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=qr.utils.get_qrcode_img_path),
        ),
    ]
