# Generated by Django 2.2.6 on 2019-10-10 04:06

from django.db import migrations, models
import qr.utils


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='label',
            field=models.CharField(default=qr.utils.label_generator, max_length=18, unique=True),
        ),
    ]
