# Generated by Django 2.2.3 on 2019-09-16 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logos.Logo'),
        ),
    ]
