# Generated by Django 2.2.6 on 2019-10-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQrCode',
            fields=[
                ('urlqrcode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qr.URLQrCode')),
            ],
            options={
                'abstract': False,
            },
            bases=('qr.urlqrcode',),
        ),
    ]
