# Generated by Django 2.2.6 on 2019-10-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qrcode_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ('id',)},
        ),
    ]
